services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Api/Dockerfile

    ports:
        - "5000:8080"
    depends_on:
      - mongo
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Mongo=mongodb://mongo:27017

    networks:
      - api
      - db
  mongo:
    image: mongo
    ports:
      - "27019:27017" 
    networks:
      - db

networks:
    api:
    db:



 

